name: Container Image CI

on:
  push:
    branches: [ "rewrite-dockerfile" ]
  pull_request:
    branches: [ "rewrite-dockerfile" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to package registry
      uses: docker/login-action@v1
      with:
        registry: https://code.cozy.town/
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Build and push Base image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./container/base/Dockerfile
        push: true
        tags: code.cozy.town/codeforleipzig/stadtratmonitor/base:latest

    - name: Build and push Deploy image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./container/deploy/Dockerfile
        push: true
        tags: code.cozy.town/codeforleipzig/stadtratmonitor/deploy:latest

    - name: Build and push Develop image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./container/develop/Dockerfile
        push: true
        tags: code.cozy.town/codeforleipzig/stadtratmonitor/develop:latest

    - name: Build and push Test image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./container/test/Dockerfile
        push: true
        tags: code.cozy.town/codeforleipzig/stadtratmonitor/test:latest